version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/agathver/coffee-beans
    steps:
      - checkout
      - run: go vet ./...
      - run: go test -v ./...
